name: schedulers
description: Dart library for running asynchronous functions on time. Useful for load balancing, rate limiting, lazy execution.
repository: https://github.com/rtmigo/schedulers

version: 1.0.3

environment:
  sdk: "^3.9.0"

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.21.6
  lints: ^6.0.0
  very_good_analysis: ^10.0.0
